project:
  type: book
  output-dir: docs

book:
  title: "Taxonomic Homogenization Deep Time"
  subtitle: "Supplementary files for: Synergy of severe climate change and extinctions results in taxonomic homogenization in deep time"
  author: "Anonymous"
  chapters:
    - index.qmd
    - 02_AllCalcs.qmd
    - 03_Fig3.qmd
    - 04_Fig2.qmd

format:
  html:
    toc: true
    toc-location: left
    base-url: /Taxonomic-Homogenization-DeepTime/

